spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?sslmode=require&prepareThreshold=0
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          preferred_instant_jdbc_type: TIMESTAMP
  flyway:
    locations: classpath:db/postgres
    baseline-on-migrate: false

CORS_ALLOWED_ORIGINS: "https://${VERCEL_PROJECT_PRODUCTION_URL:project-rub88.vercel.app},https://${VERCEL_URL:project-rub88.vercel.app}"
