-- Baseline migration to initialize Flyway tracking
-- Core table migrations (conversations, messages, participants, blocks, reports) will be introduced in subsequent domain phases.
SELECT 1;

-- V1: Create conversations table
CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_message_id BIGINT NULL,
    last_message_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_conversations_public_id UNIQUE (public_id),
    CONSTRAINT chk_conversations_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'CLOSED'))
);

CREATE INDEX idx_conversations_last_msg_at ON conversations(last_message_at DESC);

-- V2: Create conversation_participants table
CREATE TABLE conversation_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT NULL,
    is_muted BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_participants_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT uk_participant_conversation_user UNIQUE (conversation_id, user_id)
);

CREATE INDEX idx_participants_user_id ON conversation_participants(user_id);
CREATE INDEX idx_participants_user_conv ON conversation_participants(user_id, conversation_id);

-- V3: Create messages table
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    client_message_id VARCHAR(100) NULL,
    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    status VARCHAR(20) NOT NULL DEFAULT 'SENT',
    content TEXT NOT NULL,
    reply_to_message_id BIGINT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted_at TIMESTAMP(3) NULL,
    CONSTRAINT uk_messages_public_id UNIQUE (public_id),
    CONSTRAINT uk_messages_sender_client_msg UNIQUE (sender_id, client_message_id),
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_reply_to FOREIGN KEY (reply_to_message_id) REFERENCES messages(id) ON DELETE SET NULL,
    CONSTRAINT chk_messages_type CHECK (message_type IN ('TEXT', 'SYSTEM', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE')),
    CONSTRAINT chk_messages_status CHECK (status IN ('SENT', 'DELIVERED', 'READ', 'EDITED', 'DELETED', 'FAILED'))
);

-- High performance composite index for cursor-based backward pagination
CREATE INDEX idx_messages_conv_created_id ON messages(conversation_id, created_at DESC, id DESC);
CREATE INDEX idx_messages_sender_id ON messages(sender_id);
CREATE INDEX idx_messages_conv_unread ON messages(conversation_id, id);

-- V4: Create blocks table
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id BIGINT NOT NULL,
    blocked_user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_blocks_pair UNIQUE (blocker_user_id, blocked_user_id),
    CONSTRAINT chk_blocks_no_self_block CHECK (blocker_user_id <> blocked_user_id)
);

CREATE INDEX idx_blocks_blocked_user ON blocks(blocked_user_id);

-- V5: Create reports table
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    conversation_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    reported_user_id BIGINT NOT NULL,
    message_id BIGINT NULL,
    reason VARCHAR(30) NOT NULL,
    description VARCHAR(1000) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_reports_public_id UNIQUE (public_id),
    CONSTRAINT fk_reports_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL,
    CONSTRAINT chk_reports_reason CHECK (reason IN ('SPAM', 'HARASSMENT', 'SCAM', 'THREATS', 'INAPPROPRIATE_CONTENT', 'OTHER')),
    CONSTRAINT chk_reports_status CHECK (status IN ('PENDING', 'REVIEWED', 'DISMISSED', 'ACTIONED'))
);

CREATE INDEX idx_reports_conversation_id ON reports(conversation_id);
CREATE INDEX idx_reports_status ON reports(status);

-- V6: Create users required by phone-number authentication and discovery.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT UK_users_email UNIQUE (email),
    CONSTRAINT UK_users_phone UNIQUE (phone),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE INDEX idx_users_status ON users(status);
