CREATE TABLE realtime_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient BIGINT NOT NULL,
    destination VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX idx_realtime_created ON realtime_events(created_at);
CREATE TABLE realtime_sessions (
    session_id VARCHAR(100) PRIMARY KEY,
    instance_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    touched_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    connected BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_realtime_sessions_user ON realtime_sessions(user_id, touched_at);
